### PR TITLE
[Feature] resources module

### LINKED ISSUE #7: View resources
View list of resources
View single resource

if user is the owner owner of a resource
  - Edit resource button
  - Delete resource button

If user is not logged in, they should be able to view resource without the react and comment functionalities, but only the share feature

### LINKED ISSUE #8: Implement Create Resource
Name
Slug
Description
image(s)/video link(s)
Create resource button
Select category

optionally:
Add to list / create list

### LINKED ISSUE #9: Manage Lists
View all user lists
On select single list: view all resources under list

if list belongs to user
View edit button on single list
View delete button on single list

view related lists

### PR DESCRIPTION
**Pull request by Cressence**
## Description
/resources
/lists

Fixes #9 #8 #7 

## How Has This Been Tested?
yarn test

## Screenshots
Screen Shot 2020-05-30 at 23 24 04
Screen Shot 2020-05-27 at 02 17 40
Screen Shot 2020-05-23 at 13 35 12
Screen Shot 2020-05-23 at 13 34 49
Screen Shot 2020-05-30 at 23 29 12
Screen Shot 2020-05-30 at 23 29 21
Screen Shot 2020-05-30 at 23 29 30
Screen Shot 2020-05-30 at 23 29 39

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by wadleo** [comment]
@Cressence please can you do the codacy fixes? I have reviewed this PR already.

**Comment by wadleo** [comment]
@Cressence please can you do the codacy fixes? I have reviewed this PR already.

**Review by wadleo — APPROVED** [review]
LGTM

**Review by sonegillis — APPROVED** [review]

**Review by gastonche — APPROVED** [review]
Tests pass so I am approving

**Pull request merged**
