### PR TITLE
Edit User Profile component

### LINKED ISSUE #5: Edit User Profile
Username and Email fields disabled
First name
lastname
Number
Profile pic
Country
Region/State
City
Street

### LINKED ISSUE #6: View User Profile
User profile pic
Username
Date of account creation
List of resources
List of land listings

### PR DESCRIPTION
**Pull request by Cressence**
## Description
User can update their information
`/profile`

Fixes #5 

## How Has This Been Tested?
To test, run
`yarn test`

## Screenshots
Screen Shot 2020-05-22 at 18 08 55

Screen Shot 2020-05-22 at 18 09 17

Screen Shot 2020-05-22 at 18 16 56

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by gastonche** [comment]
@Cressence could you pull develop into this branch to bring it up to date and solve these merge conflicts. The public files have been removed from git so you will need to delete them so that they do not get introduced into the git tracking again

**Comment by gastonche** [comment]
Also @Cressence Codacy tests are failing here. Please check to see what is failing.

**Comment by gastonche** [comment]
But the work look good to me. Good work

**Comment by Cressence** [comment]
> @Cressence could you pull develop into this branch to bring it up to date and solve these merge conflicts. The public files have been removed from git so you will need to delete them so that they do not get introduced into the git tracking again

Okay will do that

**Review by gastonche — APPROVED** [review]
LGTM

**Review by wadleo — APPROVED** [review]
Ran it locally, ran tests, LGTM

**Review by sonegillis — APPROVED** [review]

**Pull request merged**
