### PR TITLE
Ft reset password #4

### LINKED ISSUE #4: Reset Password
Email
Reset password button
Link to login

### PR DESCRIPTION
**Pull request by Cressence**
## Description
Complete reset and confirm password component
/reset-password
/confirm-password

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #4 

## How Has This Been Tested?
yarn test

## Screenshots (if applicable, else remove this line / section)
Screen Shot 2020-05-18 at 23 23 18

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by sonegillis — CHANGES_REQUESTED** [review]
Looks good. But I suggest you bold the heading **Confirm Pasword** and also bold and Italize the users email _**test@test.com**_. A screenshot of the mobile view too will do

**Review by gastonche — CHANGES_REQUESTED** [review]
I think the title reset password should be bolder

**Comment by Cressence** [comment]
Screen Shot 2020-05-19 at 11 42 53

Mobile view
Screen Shot 2020-05-19 at 11 43 06

2)
Screen Shot 2020-05-19 at 11 50 45

Mobile view
Screen Shot 2020-05-19 at 11 51 00

3)
Screen Shot 2020-05-19 at 12 28 31

Mobile view
Screen Shot 2020-05-19 at 11 51 22

**Review by sonegillis — DISMISSED** [review]
Looks good to me @Cressence so I'll approve

**Review by wadleo — DISMISSED** [review]
Ran it locally, tests passed and LGTM

**Review by gastonche — DISMISSED** [review]

**Review by gastonche — DISMISSED** [review]

**Review by wadleo — DISMISSED** [review]
Tested locally, ran tests and LGTM

**Pull request closed without merging**
