### PR TITLE
[app properties] added app properties based on new properties provided

### PR DESCRIPTION
**Pull request by gastonche**
## Description
App properties needed for evaluation by Andela have been updated

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by wadleo — COMMENTED** [review]
Hey @gastonche, did you intentionally add the last file(in the public folder) here

**Comment by gastonche** [comment]
> Hey @gastonche, did you intentionally add the last file(in the public folder) here

must have been added when I updated the branch with develop. I'll delete it

**Comment by gastonche** [comment]
@wadleo it's not being tracked so it's fine.

**Review by wadleo — APPROVED** [review]
LGTM

**Review by Cressence — APPROVED** [review]

**Review by sonegillis — APPROVED** [review]

**Pull request merged**
