### PR TITLE
Ft home page design

### LINKED ISSUE #1: Build Home Page
1. Display description of services provided
1. Display "why you want to use this site" section
1. Footer
1. Header: Login and sign up Links

### PR DESCRIPTION
**Pull request by gastonche**
## Description
Home page design for the app has been implemented and only the content is left to be put it.
Also added an HTTP Client that can be used to create an http server to communicate with out servers, with some level of flexibility.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #1 

## How Has This Been Tested?
Has been tested on on the browser to ensure the page is responsive enough

## Screenshots (if applicable, else remove this line / section)
screencapture-localhost-8000-2020-05-17-02_27_32
screencapture-localhost-8000-2020-05-17-02_27_46
screencapture-localhost-8000-2020-05-17-02_28_02

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Cressence — APPROVED** [review]
Looks great!!

**Review by wadleo — APPROVED** [review]
Run it locally, LGTM

**Comment by wadleo** [comment]
@gastonche I just realized no tests were written for the home-page component.

**Comment by gastonche** [comment]
@sonegillis Your review is pending here

**Review by sonegillis — APPROVED** [review]

**Pull request merged**
