### PR TITLE
Build sign-in component

### LINKED ISSUE #3: Login
Email
Password
Link to reset password
Login button

When account is not verified, show verify account dialog which
- Contains user email
- Contains send verification button.

### PR DESCRIPTION
**Pull request by Cressence**
## Description
Screen Shot 2020-05-18 at 14 14 38

Fixes #3 

## How Has This Been Tested?
run yarn test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by wadleo — DISMISSED** [review]
Ran it locally, run tests, it LGTM

**Review by gastonche — DISMISSED** [review]

**Comment by gastonche** [comment]
@wadleo @sonegillis please re review this. I need it this night.

@Cressence please check why circle CI tests fail on this

**Review by gastonche — APPROVED** [review]

**Review by wadleo — CHANGES_REQUESTED** [review]
The code looks okay but the header test fails locally, @Cressence can you check why this is happening

**Review by gastonche — DISMISSED** [review]

**Review by gastonche — APPROVED** [review]

**Review by wadleo — APPROVED** [review]
Ran locally with all test passing. Just one small recommendation though, some links on the site are not yet working like the sign-up link on this page, I guess you guess will fix all that before the demo right? I will just approve this so we can move ahead, I guess you guys are thinking of that.

**Review by sonegillis — APPROVED** [review]

**Pull request merged**
